# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  #- name: CV
  #  url: /#cv
  #  weight: 11
  - name: Papers
    url: /#papers
    weight: 12
  - name: Talks
    url: /#talks
    weight: 13
  - name: Events
    url: /#events
    weight: 15
  - name: CV
    url: cv/
    weight: 20
  - name: Teaching
    url: teaching/
    weight: 30
  - name: Contact
    url: contact_page/
    weight: 40
  #- name: Experience
  #  url: experience/
  #  weight: 20
  #- name: Projects
  #  url: projects/
  #  weight: 30
  #- name: Teaching
  #  url: teaching/
  #  weight: 40
